---
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_gitconfig:
    src: dotfiles/.gitconfig
    dst: ~/.gitconfig
  f_zshrc:
    src: dotfiles/.zshrc
    dst: ~/.zshrc
  f_golangci.yml:
    src: dotfiles/.golangci.yml
    dst: ~/.golangci.yml
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_vale.ini:
    src: vale.ini
    dst: ~/.vale.ini
  f_functions:
    src: config/zsh/functions
    dst: ~/.config/zsh/functions
    chmod: '644'
  f_scroll.py:
    src: config/kitty/scroll.py
    dst: ~/.config/kitty/scroll.py
  f_kitty_opener.sh:
    src: config/nvim/lua/scripts/kitty_opener.sh
    dst: ~/.config/nvim/lua/scripts/kitty_opener.sh
    chmod: '744'
  f_accounting-startup.sh:
    src: scripts/accounting-startup.sh
    dst: ~/scripts/accounting-startup.sh
    chmod: '744'
  f_nvim-startup.sh:
    src: scripts/nvim-startup.sh
    dst: ~/scripts/nvim-startup.sh
    chmod: '744'
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_awesome:
    src: config/awesome
    dst: ~/.config/awesome
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_scripts:
    src: scripts
    dst: ~/scripts
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  d_tridactyl:
    src: config/tridactyl
    dst: ~/.config/tridactyl
  d_screenlayout:
    src: config/screenlayout
    dst: ~/.config/screenlayout
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_styles:
    src: styles
    dst: ~/styles
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
profiles:
  foundant-wolf:
    dotfiles:
      - f_gitconfig
      - f_zshrc
      - f_golangci.yml
      - f_xmodmap
      - f_functions
      - f_vale.ini
      - f_scroll.py
      - f_kitty_opener.sh
      - f_accounting-startup.sh
      - f_nvim-startup.sh
      - d_i3
      - d_kitty
      - d_nvim
      - d_polybar
      - d_rofi
      - d_scripts
      - d_ranger
      - d_tridactyl
      - d_screenlayout
      - d_picom
      - d_styles
      - d_zsh
    variables:
      adapter: AC
      battery: BAT0
  to-wolf:
    dotfiles:
      - f_gitconfig
      - f_zshrc
      - f_golangci.yml
      - f_functions
      - f_vale.ini
      - f_scroll.py
      - f_kitty_opener.sh
      - f_nvim-startup.sh
      - d_kitty
      - d_nvim
      - d_scripts
      - d_ranger
      - d_tridactyl
      - d_styles
      - d_zsh
      - d_sway
      - d_swaylock
      - d_waybar
      - d_wofi
    variables:
      adapter: AC
      battery: BAT0
  red-wolf:
    dotfiles:
      - f_gitconfig
      - f_zshrc
      - f_golangci.yml
      - f_xmodmap
      - f_functions
      - f_vale.ini
      - f_scroll.py
      - f_kitty_opener.sh
      - f_nvim-startup.sh
      - d_i3
      - d_kitty
      - d_nvim
      - d_polybar
      - d_rofi
      - d_scripts
      - d_ranger
      - d_tridactyl
      - d_screenlayout
      - d_picom
      - d_styles
      - d_zsh
    variables:
      adapter: ADP1
      battery: BAT1
