config:
  backup: false
  create: true
  dotpath: dotfiles
dotfiles:
  f_gitconfig:
    src: dotfiles/.gitconfig
    dst: ~/.gitconfig
  f_zshrc:
    src: dotfiles/.zshrc
    dst: ~/.zshrc
  f_golangci.yml:
    src: dotfiles/.golangci.yml
    dst: ~/.golangci.yml
  f_functions:
    src: config/zsh/functions
    dst: ~/.config/zsh/functions
    chmod: '644'
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_scripts:
    src: scripts
    dst: ~/scripts
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  d_tridactyl:
    src: config/tridactyl
    dst: ~/.config/tridactyl
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  d_envman:
    src: config/envman
    dst: ~/.config/envman
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  d_swaync:
    src: config/swaync
    dst: ~/.config/swaync
  d_wlogout:
    src: config/wlogout
    dst: ~/.config/wlogout
  d_artty:
    src: config/arTTY
    dst: ~/.config/arTTY
  f_settings.ini:
    src: config/gtk-3.0/settings.ini
    dst: ~/.config/gtk-3.0/settings.ini
  d_wezterm:
    src: config/wezterm
    dst: ~/.config/wezterm
  d_foot:
    src: config/foot
    dst: ~/.config/foot
  d_hypr:
    src: config/hypr
    dst: ~/.config/hypr
profiles:
  neto-wolf:
    dotfiles:
    - f_gitconfig
    - f_zshrc
    - f_golangci.yml
    - f_functions
    - d_nvim
    - d_scripts
    - d_tridactyl
    - d_zsh
    - d_sway
    - d_swaylock
    - d_waybar
    - d_envman
    - d_swaync
    - d_gtk-3.0
    - d_wlogout
    - d_artty
    - f_settings.ini
    - d_wezterm
    - d_foot
    - d_hypr
  red-wolf:
    dotfiles:
    - f_gitconfig
    - f_zshrc
    - f_golangci.yml
    - f_functions
    - d_waybar
    - d_nvim
    - d_scripts
    - d_tridactyl
    - d_zsh
    - d_sway
    - d_swaylock
    - d_swaync
    - d_envman
    - d_gtk-3.0
    - d_wlogout
    - d_artty
    - f_settings.ini
    - d_wezterm
    - d_foot
    - d_hypr
