config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_awesome:
    src: config/awesome
    dst: ~/.config/awesome
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_scripts:
    src: scripts
    dst: ~/scripts
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_git-prompt.sh:
    src: git-prompt.sh
    dst: ~/.git-prompt.sh
  f_gitconfig:
    src: dotfiles/.gitconfig
    dst: ~/.gitconfig
  f_tmux.conf:
    src: dotfiles/.tmux.conf
    dst: ~/.tmux.conf
  f_zshrc:
    src: dotfiles/.zshrc
    dst: ~/.zshrc
  f_golangci.yml:
    src: dotfiles/.golangci.yml
    dst: ~/.golangci.yml
  d_icons:
    src: dotfiles/.icons
    dst: ~/.icons
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_dashboard.cat:
    src: config/nvim/dashboard.cat
    dst: ~/.config/nvim/dashboard.cat
    chmod: '644'
  f_zsh_zshrc:
    src: config/zsh/.zshrc
    dst: ~/.config/zsh/.zshrc
  f_aliases:
    src: config/zsh/aliases
    dst: ~/.config/zsh/aliases
  f_paths:
    src: config/zsh/paths
    dst: ~/.config/zsh/paths
  f_plugins:
    src: config/zsh/plugins
    dst: ~/.config/zsh/plugins
  f_theme:
    src: config/zsh/theme
    dst: ~/.config/zsh/theme
profiles:
  foundant-wolf:
    dotfiles:
    - d_i3
    - d_kitty
    - d_nvim
    - d_polybar
    - d_rofi
    - d_scripts
    - f_gitconfig
    - f_zshrc
    - f_golangci.yml
    - d_icons
    - d_ranger
    - f_xmodmap
    - f_dashboard.cat
    - f_zsh_zshrc
    - f_aliases
    - f_paths
    - f_plugins
    - f_theme
    variables:
      adapter: AC
      battery: BAT0
  red-wolf:
    dotfiles:
    - d_i3
    - d_kitty
    - d_nvim
    - d_polybar
    - d_rofi
    - d_scripts
    - f_bashrc
    - f_gitconfig
    - f_zshrc
    - f_golangci.yml
    - d_icons
    - d_ranger
    - f_xmodmap
    - f_zsh_zshrc
    - f_aliases
    - f_paths
    - f_plugins
    - f_theme
    variables:
      adapter: ADP1
      battery: BAT1
