#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_filetree_gitstatus = true
    enable_statusline_mode = false
    filetree_direction = "left"

### GENERAL ###
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "colorscheme"

[[layers]]
name = 'checkers'
lint_on_the_fly = true 
lint_on_save = true

[[layers]]
name = 'lsp'
filetypes = [
  'css',
  'html',
  'javascript',
  'sh',
  'typescript'
  'go'
]

[[layers]]
name = "lang#ui"
enable_scrollbar = true

[[layers]]
name = "denite"

[[layers]]
name = 'debug'

[[layers]]
name = "incsearch"

### GIT ###
[[layers]]
name = 'git'
git-plugin = 'fugitive'

[[layers]]
name = 'VersionControl'

### GO ###
[[layers]]
name = "lang#go"


### JS/TS ###
[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#typescript"



