# https://alacritty.org/config-alacritty.html

[font]
{%@@ if profile == "red-wolf" or profile == "vm" @@%}
size = 13
{%@@ else @@%}
size = 15
{%@@ endif @@%}

[font.bold]
family = "Sudo"
style = "Bold"

[font.bold_italic]
family = "Sudo"
style = "Bold Italic"

[font.italic]
family = "Sudo"
style = "Italic"

[font.normal]
family = "Sudo"
style = "Regular"

# Default colors
[colors.primary]
background = '#1f2329'
foreground = '#a0a8b7'

# Cursor colors
[colors.cursor]
text = '#a0a8b7'
cursor = '#8420f5'

# Normal colors
[colors.normal]
black   = '#0e1013'
red     = '#fe4450'
green   = '#72f1b8'
yellow  = '#FFCC00'
blue    = '#3A47FF'
magenta = '#AF6DF9'
cyan    = '#61E2FF'
white   = '#EBEBEB'

# Bright colors
[colors.bright]
black   = '#101216'
red     = '#f7202e'
green   = '#0ff58e'
yellow  = '#FFF700'
blue    = '#3A89FF'
magenta = '#8420f5'
cyan    = '#0081A1'
white   = '#FEFEF8'

[keyboard]
bindings = [
   # { key = '_', mods = "Control|Shift", chars = "\uE001" },
]
