# https://alacritty.org/config-alacritty.html
[window]
padding = { x = 3, y = 3 }
resize_increments = true
{%@@ if profile == "vesal-wolf" @@%}
option_as_alt = "Both"
{%@@ endif @@%}

[font]
{%@@ if profile == "red-wolf" or profile == "vm" @@%}
size = 11
{%@@ elif profile == "veasal-wolf" @@%}
size = 16
{%@@ else @@%}
size = 13
{%@@ endif @@%}

[font.bold]
family = "ShureTechMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "ShureTechMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "ShureTechMono Nerd Font"
style = "Italic"

[font.normal]
family = "ShureTechMono Nerd Font"
style = "Regular"

# Default colors
[colors.primary]
background = '#1f2329'
foreground = '#a0a8b7'

# Cursor colors
[colors.cursor]
text = '#a0a8b7'
cursor = '#8420f5'

# Normal colors
[colors.normal]
black   = '#0e1013'
red     = '#fe4450'
green   = '#72f1b8'
yellow  = '#FFCC00'
blue    = '#3A47FF'
magenta = '#AF6DF9'
cyan    = '#61E2FF'
white   = '#EBEBEB'

# Bright colors
[colors.bright]
black   = '#101216'
red     = '#f7202e'
green   = '#0ff58e'
yellow  = '#FFF700'
blue    = '#3A89FF'
magenta = '#8420f5'
cyan    = '#0081A1'
white   = '#FEFEF8'

[keyboard]
bindings = [
   # { key = '_', mods = "Control|Shift", chars = "\uE001" },
{%@@ if profile == "vesal-wolf" @@%}
   { key = 'Slash', mods = "Control", chars = "\u001F" }
{%@@ endif @@%}
]
